apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: jx-app-org
    provider: github
    repository: mint-prawn
  name: jx-app-org-mint-prawn
spec:
  description: Imported application for jx-app-org/mint-prawn
  httpCloneURL: https://github.com/jx-app-org/mint-prawn.git
  org: jx-app-org
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: mint-prawn
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/jx-app-org/mint-prawn.git
